---

name: AutoLint

on:
  push:
    branches: [latest]
  pull_request:
    branches: [latest]

jobs:
  build:
    strategy:
      matrix:
        python-version: [3.10]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Switch to Current Branch
        run: git checkout ${{ env.BRANCH }}
        shell: bash

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements_lint.txt
        shell: bash

      - name: Running PyLint
        run: pylint --recursive=y .
        shell: bash

      - name: Running YamlLint
        run: yamllint .
        shell: bash

      - name: Preparing collection for AnsibleLint
        run: |
          mkdir -p /tmp/ansible_lint/collections/ansible_collections/ansibleguy
          ln -s ${{ github.workspace }} /tmp/ansible_lint/collections/ansible_collections/ansibleguy/opnsense
        shell: bash

      - name: Running AnsibleLint
        run: ANSIBLE_COLLECTIONS_PATH=/tmp/ansible_lint/collections ansible-lint -c .ansible-lint.yml
        shell: bash
